### ISSUE TITLE
Search lines by character

### ISSUE THREAD

**Issue by WillAbides** [aackerman/lebowski-api#21]
It would be quite nice to search for lines spoken by a given character

**Comment by aackerman** [comment]
What would you imagine the API to look like?

**Comment by WillAbides** [comment]
When I posted this issue, I fully expected to follow it up with a pull request, but I got side tracked by something that was even more urgent than this.

I was thinking of something like `/api/lines/search?character=The%20Dude`.

It would also be handy to have `/api/lines/random?character=The%20Dude` to save the trouble of randomly selecting a line from the returned set.

This raises the issue of formatting of character names.  Maybe `/api/characters` could be added to handle that.
