### ISSUE TITLE
Missing quotes

### ISSUE THREAD

**Issue by nall** [aackerman/lebowski-api#22]
The following query terms don't result in any hits, though the text is listed in the .sql and .json files.

eagles
metallica
socially
huron

I tried with the lebowski CLI client as well.

**Comment by aackerman** [comment]
Not *all* of the lines from the script are represented as quotes although a good majority of them are. But all the of respective lines with be displayed for those search terms.

http://lebowski.me/api/lines/search?term=huron

The production sql dump needs to be updated, it's out of date.

You could write a PR that adds the db migration to create quotes from lines that contain those specific terms if you're interested.
